In [2]:
import json
import numpy as np
import dask_awkward as dak

In [65]:
with open("./histogram/plot_settings.json", "r") as file:
    plot_settings = json.load(file)
available_processes = ["ggh_powheg"]
# process = "vbf_powheg"
load_path = "/depot/cms/users/yun79/results/stage1/test_full"
# load_path = load_path + f"/f0_1"
load_path = load_path + f"/f0_001"
# color_map= {
#     "vbf_powheg" : 
# }
var = "jet1_pt"
binning = np.linspace(*plot_settings[var]["binning_linspace"])
data_hists = []
mc_hists = []
# dummy_hist.Draw("hist");

for process in available_processes:
    print(f"process: {process}")
    full_load_path = load_path+f"/{process}/*/*.parquet"
    events = dak.from_parquet(full_load_path) 
    print(events.fields)

process: ggh_powheg
['mu1_pt', 'mu2_pt', 'mu1_eta', 'mu2_eta', 'mu1_phi', 'mu2_phi', 'mu1_iso', 'mu2_iso', 'dimuon_mass', 'dimuon_ebe_mass_res', 'dimuon_ebe_mass_res_rel', 'dimuon_pt', 'dimuon_eta', 'dimuon_phi', 'dimuon_dEta', 'dimuon_dPhi', 'dimuon_dR', 'dimuon_cos_theta_cs', 'dimuon_phi_cs', 'jet1_pt', 'jet1_eta', 'jet1_rap', 'jet1_phi', 'jet1_qgl', 'jet1_jetId', 'jet1_puId', 'jet2_pt', 'jet2_eta', 'jet2_rap', 'jet2_phi', 'jet2_qgl', 'jet2_jetId', 'jet2_puId', 'jj_mass', 'jj_pt', 'jj_eta', 'jj_phi', 'jj_dEta', 'jj_dPhi', 'mmj1_dEta', 'mmj1_dPhi', 'mmj1_dR', 'mmj2_dEta', 'mmj2_dPhi', 'mmj2_dR', 'mmj_min_dEta', 'mmj_min_dPhi', 'mmjj_pt', 'mmjj_eta', 'mmjj_phi', 'mmjj_mass', 'rpt', 'zeppenfeld', 'njets', 'nBtagLoose', 'nBtagMedium', 'z_peak', 'h_sidebands', 'h_peak', 'vbf_cut', 'fraction', 'gjj_mass', 'gjet1_pt', 'gjet2_pt', 'gjet1_eta', 'gjet2_eta', 'gjet1_phi', 'gjet2_phi', 'gjet1_mass', 'gjet2_mass', 'gjj_dEta', 'gjj_dPhi', 'gjj_dR', 'weight_nominal']


In [6]:
#checkt that there's no None values
import awkward as 

arr = ak.fill_none((events.h_sidebands.compute() | events.h_peak.compute()), value=-999)
print(ak.sum(arr==-999))

In [19]:
np_arr.shape

(129926,)

In [20]:
np_arr[np_arr==True].shape

(123090,)

In [21]:
plot_settings[var]["binning_linspace"]

[25, 300, 30]

In [78]:
test_binning = np.linspace(0,8,8)
np_array = np.ones(5)
np_weight = np.ones(5)
np_weight[2:4] = 0
np_hist, edges = np.histogram(np_array, bins=test_binning, weights=np_weight)
np_hist

array([3., 0., 0., 0., 0., 0., 0.])

In [85]:
np_hist*2

array([6., 0., 0., 0., 0., 0., 0.])

In [66]:
vbf_cut = ak.fill_none(events.vbf_cut, value=False) # in the future none values will be replaced with False
region = events.h_sidebands | events.h_peak
btag_cut =(events.nBtagLoose >= 2) | (events.nBtagMedium >= 1)
cat_selection = (
    ~vbf_cut & # we're interested in ggH category
    region &
    btag_cut # btag cut is for VH and ttH categories
).compute()
cat_selection = ak.to_numpy(cat_selection)
cat_selection[cat_selection].shape

(608,)

In [67]:
ak.num(events.h_sidebands, axis=0).compute()
cat_selection

641

In [83]:
cat_selection * 1/2

array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0. , 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0. , 0.5, 0.5, 0.5, 0. , 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0. , 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0. ,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0. , 0.5, 0.5, 0.5,
       0.5, 0. , 0.5, 0.5, 0.5, 0.5, 0.5, 0. , 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0. ,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0. , 0.5,
       0.5, 0.5, 0.5, 0.5, 0. , 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.